### ISSUE TITLE
sorry i'm keep opening issues ! but one question + one typo

### ISSUE THREAD

**Issue by Aeilxs** [manojsethi/nest_auth_demo_refresh_token#2]
here is a reason why you do this ?

```ts
// src/users/users.controller.ts
@Get()
  async findAll(): Promise<User[]> {
    return (await this.usersService.findAll()).map((x) => new User(x));
  }
```

instead of just `return await this.usersService.findAll()` ?

also there is another typo in src/common/guards you have gaurds instead ^^' anyway thanks for sharing  this it helped me a lot, are you planning to do unit testing on this ?

in my opinion in the auth service you should extract in a method the checkUsersExist

```ts
// signUp
    const userExists = await this.usersService.findByEmail(createUserDto.email);
    if (userExists) {
      throw new BadRequestException('User already exists');
    }

//signIn
    const user = await this.usersService.findByEmail(data.email);
    if (!user) throw new BadRequestException('User does not exist');
```

i did this

```ts
  private async checkUserExists(email: string, msg: string): Promise<void> {
    const userExists = await this.usersService.findByEmail(email);
    if (userExists) {
      throw new BadRequestException(msg);
    }
  }
```

also i believe you shouldn't send an error 'password is incorrect' since it's not recommended

**Comment by manojsethi** [comment]
> instead of just `return await this.usersService.findAll()` ?

I have used (await this.usersService.findAll()).map((x) => new User(x)); to take advantage of Class Serializer else you will see all properties in your response.

Regarding the unit tests I do have a plat but not at the moment, I will try to keep updating little by little.

Regarding the password surely you can omit it, I just created it to play with some of my other demo projects and wanted to keep it as a starter.
